### ISSUE TITLE
Why there is no cache for images?

### ISSUE THREAD

**Issue by FDiskas** [kingkool68/dummyimage#1]
Why not just put all generated images to the cloud? And after requesting them redirect to cloud?

**Comment by KingMario** [comment]
Then the images will occupy a lot of cloud space beyond an individual can afford, I guess.

**Comment by FDiskas** [comment]
And its costs like nothing https://aws.amazon.com/s3/pricing/

**Comment by kingkool68** [comment]
https://dummyimage.com gets over a million requests a day. The server itself (configured using https://easyengine.io/) is set-up to use Redis to serve the images from cache once they're generated. It's hosted on https://www.dreamhost.com/cloud/computing/ for $6/month.
