### ISSUE TITLE
Recent update broke images with symbols or spaces in text

### ISSUE THREAD

**Issue by skeddles** [kingkool68/dummyimage#25]
I've been using this to generate a daily hashtag, and a few days ago it stopped working properly.

My format looks like this:

`https://dummyimage.com/256x256/332f35/ffffff.png&text=%23movie`

Now on generated images it's writing the text as the resolution, as seen below:
![ffffff](https://user-images.githubusercontent.com/2721332/141693580-ed99587b-ba79-4286-b1a0-23513455acd2.png)

After a bit of testing, I've found that it's the `#` symbol that's breaking it. Changing the request to

`https://dummyimage.com/256x256/332f35/ffffff.png&text=movie`

properly outputs the text "movie".

I've tried using just `#` instead of the url encoded version, but that too returns the resolution.

It seems to break any time there's a url encoded symbol. Sometimes the symbols work when not encoded, such as `$movie`, but `%24movie` still breaks it, as does `#movie`

**Comment by digitalescapade** [comment]
Hi,

I noticed that spaces don't work anymore too. For example : https://dummyimage.com/256x256/332f35/ffffff.png&text=good+movie won't work.

@kingkool68 Will you be able to fix this or shall we find an alternative solution for production ? Do you ave ETA ?

Thanks for your great work

**Comment by kingkool68** [comment]
Fixed with https://github.com/kingkool68/dummyimage/commit/a7b14bc3e2c1b3382d837bbc207a8ae5847b8e50

https://dummyimage.com/600x40/007cba/fff.png&text=All+fixed+and+good+to+go!
