### ISSUE TITLE
"qvga" shortcut results in a "Too small of an image!" response

### ISSUE THREAD

**Issue by Andre601** [kingkool68/dummyimage#27]
Using the [qvga](https://dummyimage.com/qvga) short code for an image will result in the site responding with "Too small of an image!" while the dimensions it should have (320x240) work perfectly fine.

**Comment by Andre601** [comment]
Quick update.
I tested the different shortcuts and the following ones do not work:

- Literally all of the `Screen Standards` section:
  - cga
  - qvga
  - vga
  - wvga
  - svga
  - wsvga
  - xga
  - wxga
  - wuxga
  - wqxga
- ntsc
- pal

Note: `hd720` and `hd1080` both return a square image and not the dimensions mentioned.

Note 2: The mention that you need to use the multiplication symbol (`×`) instead of `x` for text seems... wrong?
Weirdly enough does the one using the normal `x` work just fine, but the `×` causes a "Too big of an image!" message to be shown.

**Comment by kingkool68** [comment]
These have all been fixed.

 - https://dummyimage.com/cga
 - https://dummyimage.com/qvga
 - https://dummyimage.com/vga
- https://dummyimage.com/wvga
- https://dummyimage.com/svga
- https://dummyimage.com/wsvga
- https://dummyimage.com/xga
- https://dummyimage.com/wxga
- https://dummyimage.com/wuxga
- https://dummyimage.com/wqxga
