### ISSUE TITLE
Can you elaborate the nginx.conf please?

### ISSUE THREAD

**Issue by debanjanbasu** [kingkool68/dummyimage#3]
I am trying to configure the nginx server to implement the nginx.conf. Can you please elaborate the steps in the Readme please?

**Comment by shabbir-dhangot** [comment]
@debanjanbasu did you find an answer? For me its saying page isn't working

**Comment by Smashr** [comment]
nginx.conf does not seem to be working. Any of you find a solution to this ?

**Comment by kingkool68** [comment]
I have just simplified the rewrite rules for dummyimage.com to work. Now named image sizes like `hd1080` and `skyscraper` are handled by the PHP code and not rewrite rules. For nginx to work You should just need to add these two rules somewhere in your site's server conf:

```
error_page 404 = @404;
location @404 {
   rewrite (.*) /code.php?x=$request_uri last;
}

rewrite (.*) /code.php?x=$request_uri last;
```

See https://github.com/kingkool68/dummyimage/blob/9ec16b9c728a1a63a10fc6004d96198c6350cd84/nginx.conf

See #38 and the PR #39 for more details.
