### ISSUE TITLE
"hd1080" renders as 1080x1080 image rather than mentioned 1920x1080

### ISSUE THREAD

**Issue by Andre601** [kingkool68/dummyimage#30]
When using [`hd1080`](https://dummyimage.com/hd1080) is the returned image in the dimensions 1080x1080 and not 1920x1080 as mentioned on the website.

This should be corrected.

**Comment by kingkool68** [comment]
This is now fixed. See https://dummyimage.com/hd1080 which should show you a 1920x1080 sized image.
