### ISSUE TITLE
.htaccess seems to work fine on Apache, but nginx.conf is ignored when we migrated to nginx.

### ISSUE THREAD

**Issue by Smashr** [kingkool68/dummyimage#33]
So we migrated from Apache to nginx and the nginx.conf file seems to be ignored completely. It works if URL parameters are sent directly to code.php, but not if the URL does not include "/code.php?...."

**Comment by Smashr** [comment]
So basically the .htaccess is working fine in Apache. But nginx.conf is not working on nginx.

**Comment by MatthiasKunnen** [comment]
nginx does not scan the directory for `nginx.conf` files like apache does for `.htaccess`. Rather, you should tell nginx that a config file exists at a specific place.

You most likely have a `/etc/nginx/sites-available` directory containing the config files for your domains, you need to edit or create the dummyimage config like this:
```nginx
server {
        server_name dummyimage.yourdomain.com;
        root /var/www/dummyimage;

        include /var/www/dummyimage/nginx.conf; # <-- you need to add this
     
        ...
}
```

And then reload nginx.

**Comment by kingkool68** [comment]
Hope you got this working. Sounds like an nginx configuration issue on the users end.
