### ISSUE TITLE
CDN on https://dummyimage.com/

### ISSUE THREAD

**Issue by jonasburneika** [kingkool68/dummyimage#35]
Hi, I know that this is more to the lib-related issues. But I can't find other contacts.
website https://dummyimage.com/ has started to use CloudFlare and is using image conversion to other formats (webP and avif)

But this is bad. You can't download any jpg image, because all of them are converted to webp. And the whole point for this website is lost.

**Comment by fushihara** [comment]
I agree with you.
I specified png in the url but the webp binary was transferred.
At the very least, there should be a note of caution near the image format selection dropdown.

**Comment by sashabeep** [comment]
+1 to that!

**Comment by sashabeep** [comment]
@kingkool68 Can you please take a look? All the pictures served in webp instead of specified

**Comment by kingkool68** [comment]
I'm looking into this. A couple months ago I added Ezoic for ads which requires proxying through their Cloudflare setup. I found the setting to turn off automatic image optimization. After an hour and checking newly generated images they are still being served as webp. I have opened up a ticket with their support community at https://community.ezoic.com/d/22493-how-to-disable-serving-all-images-as-webp 

I'll let you know if I hear back.

**Comment by kingkool68** [comment]
Looks like this is now fixed. Here's an image with a `.jpg` extension and the content type being returned is `image/jpg` as expected.

![Screenshot 2023-08-07 at 8 40 56 PM](https://github.com/kingkool68/dummyimage/assets/867430/233a1666-f656-466c-8355-289bfdfd3986)
